-- =====================================================================
-- Add 'needs_review' to the requirement_status.status CHECK constraint
-- so the self-heal policy can flag stuck items without blocking the flow.
--
-- Idempotent and defensive:
--   1) Diagnose — print the distinct values currently stored.
--   2) Normalize obvious alias (`canceled` → `cancelled`).
--   3) Drop the prior CHECK (if any).
--   4) Re-add a CHECK that is the UNION of
--        (a) the legacy domain the route.ts tool has been writing,
--        (b) the extended 'needs_review' value used by self-heal.
--   5) If any row still violates the new domain, raise a clear error
--      listing the offending value(s) so the operator can decide whether
--      to add another alias mapping above or clean the rows manually.
--
-- Safe to re-run.
-- =====================================================================

-- 1) Diagnose
do $$
declare
  r record;
begin
  raise notice '--- requirement_status distinct statuses (before migration) ---';
  for r in
    select status, count(*) as n
    from public.requirement_status
    group by status
    order by n desc
  loop
    raise notice 'status=% count=%', coalesce(r.status, '<null>'), r.n;
  end loop;
end
$$;

-- 2) Normalize legacy data:
--    2a) Alias (British vs American, underscore vs dash).
update public.requirement_status
   set status = 'cancelled'
 where status = 'canceled';

update public.requirement_status
   set status = 'in-progress'
 where status = 'in_progress';

--    2b) Historically the `status` column was abused as a free-form progress
--        message (entries like "Instancia y Plan de agente creados",
--        "Cierre Final", "Entregable Validado", etc.). Those belong in
--        `message`. We move them there (prepending if `message` already
--        exists) and coerce `status` to the closest canonical value based on
--        the semantic family of the phrase.
update public.requirement_status
   set message = case
                   when message is null or trim(message) = '' then status
                   else status || ' | ' || message
                 end,
       status  = case
                   -- Rejection / returned to backlog
                   when status ilike '%devuelto%'
                     or status ilike '%fallo%'
                     or status ilike '%falla%'
                     or status ilike '%error%'
                     or status ilike '%bypass%'
                   then 'failed'
                   -- Successful closure / validated deliverable
                   when status ilike '%cierre final%'
                     or status ilike '%listo para cierre%'
                     or status ilike '%completado%'
                     or status ilike '%exitosa%'
                     or status ilike '%entregable validado%'
                     or status ilike '%entregable finalizado%'
                     or status ilike '%corrección completada%'
                     or status ilike '%aprobada%'
                   then 'completed'
                   -- Ignored / superseded → parked
                   when status ilike '%ignorado%'
                     or status ilike '%liberado%'
                   then 'cancelled'
                   -- Everything else that is clearly prose stays as in-progress.
                   else 'in-progress'
                 end
 where status is not null
   and status not in (
         'pending', 'in-progress', 'on-review', 'completed', 'done',
         'failed', 'blocked', 'paused', 'cancelled', 'backlog',
         'validated', 'needs_review'
       );

-- 3) Drop the current CHECK constraint (whatever its autogenerated name is).
do $$
declare
  cname text;
begin
  select conname into cname
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  join pg_namespace n on n.oid = t.relnamespace
  where t.relname = 'requirement_status'
    and n.nspname = 'public'
    and c.contype = 'c'
    and pg_get_constraintdef(c.oid) ilike '%status%'
  limit 1;

  if cname is not null then
    execute format('alter table public.requirement_status drop constraint %I', cname);
    raise notice 'Dropped existing constraint %', cname;
  else
    raise notice 'No pre-existing status CHECK constraint found — skipping drop.';
  end if;
end
$$;

-- 4) Pre-flight: list any row that would still violate the new domain so the
--    operator can see exactly what is blocking, BEFORE we add the constraint.
--    The offending values (and counts) are embedded directly into the
--    exception message because `RAISE NOTICE` / `RAISE WARNING` are not
--    always surfaced by the client (e.g. Supabase SQL editor).
do $$
declare
  offenders_json text;
  allowed text[] := array[
    'pending',
    'in-progress',
    'on-review',
    'completed',
    'done',
    'failed',
    'blocked',
    'paused',
    'cancelled',
    'backlog',
    'validated',
    'needs_review'
  ];
begin
  select coalesce(
           string_agg(
             format('%L (×%s)', coalesce(status, '<null>'), n),
             ', '
             order by n desc
           ),
           ''
         )
    into offenders_json
  from (
    select status, count(*) as n
      from public.requirement_status
     where status is null or not (status = any(allowed))
     group by status
  ) s;

  if offenders_json <> '' then
    raise exception
      'requirement_status rows outside target domain: % | allowed=%. '
      'Either add a normalization UPDATE earlier in this script '
      'or extend the `allowed` array to include the missing values.',
      offenders_json,
      array_to_string(allowed, ', ');
  end if;
end
$$;

-- 5) Add the new CHECK
alter table public.requirement_status
  add constraint requirement_status_status_check
  check (status in (
    'pending',
    'in-progress',
    'on-review',
    'completed',
    'done',
    'failed',
    'blocked',
    'paused',
    'cancelled',
    'backlog',
    'validated',
    'needs_review'
  ));
