import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/database/supabase-client';
import { sendGridService } from '@/lib/services/sendgrid-service';
import { z } from 'zod';

export const maxDuration = 120;

const ReservationReminderSchema = z.object({
  email: z.string().email('Invalid email address'),
  subject: z.string().min(1, 'Subject is required'),
  message: z.string().min(1, 'Message is required'),
  site_id: z.string().uuid('site_id must be a valid UUID'),
  locale: z.string().default('es')
});

function getBrandingText(): string {
  return process.env.UNCODIE_BRANDING_TEXT || 'Makinari, your AI Sales Team';
}

function getCompanyName(): string {
  return process.env.UNCODIE_COMPANY_NAME || 'Makinari';
}

// Minimal wrapper, letting the Markdown `message` be parsed or formatted safely in HTML
function generateReservationHtml(data: { siteName: string; subject: string; message: string; locale: string; logoUrl?: string }): string {
  // Convert basic markdown to HTML simply for the message text
  let formattedMessage = data.message;
  
  // Convertir encabezados h1, h2, h3
  formattedMessage = formattedMessage.replace(/^### (.*$)/gim, '<h3>$1</h3>');
  formattedMessage = formattedMessage.replace(/^## (.*$)/gim, '<h2>$1</h2>');
  formattedMessage = formattedMessage.replace(/^# (.*$)/gim, '<h1>$1</h1>');
  
  // Convertir negritas
  formattedMessage = formattedMessage.replace(/\*\*(.*)\*\*/gim, '<strong>$1</strong>');
  
  // Convertir listas
  formattedMessage = formattedMessage.replace(/^\- (.*$)/gim, '<ul><li>$1</li></ul>');
  formattedMessage = formattedMessage.replace(/<\/ul>\n<ul>/gim, '');

  // Convertir enlaces a estilo CTA centrados
  formattedMessage = formattedMessage.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<div style="text-align: center; margin: 32px 0 16px 0;"><a href="$2" target="_blank" class="email-cta" style="background: #000000; background-color: #000000; background-image: linear-gradient(#000000, #000000); box-shadow: inset 0 0 0 999px #000000; color: #ffffff; border: 0; display: inline-block; font-weight: 600; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-size: 16px; text-align: center;"><span class="email-cta-label">$1</span></a></div>');
  
  // Convertir saltos de linea restantes en <br/>
  formattedMessage = formattedMessage.replace(/\n/g, '<br/>');

  // Limpiar posibles <br/> dentro de los headers
  formattedMessage = formattedMessage.replace(/<\/h1><br\/>/gim, '</h1>');
  formattedMessage = formattedMessage.replace(/<\/h2><br\/>/gim, '</h2>');
  formattedMessage = formattedMessage.replace(/<\/h3><br\/>/gim, '</h3>');
  formattedMessage = formattedMessage.replace(/<\/ul><br\/>/gim, '</ul>');

  return `
    <!DOCTYPE html>
    <html lang="${data.locale}">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${data.subject}</title>
      <style>
        .email-cta-td {
          background-color: #000000 !important;
          background-image: linear-gradient(#000000, #000000) !important;
          box-shadow: inset 0 0 0 999px #000000 !important;
        }
        .email-cta {
          background-color: #000000 !important;
          background-image: linear-gradient(#000000, #000000) !important;
          box-shadow: inset 0 0 0 999px #000000 !important;
          color: #ffffff !important;
          -webkit-text-fill-color: #ffffff !important;
          border: 0 !important;
        }
        .email-cta-label,
        .email-cta span {
          color: #ffffff !important;
          -webkit-text-fill-color: #ffffff !important;
        }
      </style>
    </head>
    <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f8fafc; line-height: 1.6;">
      <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); overflow: hidden;">
        
        <div style="background: #1e1e2d; padding: 32px 40px; text-align: center;">
          ${data.logoUrl ? `
            <img src="${data.logoUrl}" alt="${data.siteName} Logo" style="width: 64px; height: 64px; border-radius: 50%; object-fit: cover; display: block; margin: 0 auto;" />
          ` : ''}
          <h1 style="margin: 16px 0 0; color: #ffffff; font-size: 24px; font-weight: 600;">${data.subject}</h1>
        </div>

        <div style="padding: 40px; color: #111111; font-size: 16px; line-height: 1.7;">
          ${formattedMessage}
        </div>

        <div style="background-color: #f8fafc; padding: 24px 40px; border-top: 1px solid #e2e8f0;">
          <p style="margin: 0; color: #52525b; font-size: 14px; text-align: center; line-height: 1.5;">
            Notification automatically generated by ${getCompanyName()}.<br>
          </p>
        </div>
      </div>
      
      <div style="text-align: center; margin: 24px 0;">
        <p style="margin: 0; color: #71717a; font-size: 12px;">
          Powered by <strong style="color: #000000;">${getBrandingText()}</strong>
        </p>
      </div>
    </body>
    </html>
  `;
}

export async function OPTIONS() {
  const headers = new Headers();
  headers.set('Access-Control-Allow-Origin', '*');
  headers.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
  headers.set('Access-Control-Allow-Headers', 'Content-Type, x-api-key, Authorization');

  return new NextResponse(null, { status: 204, headers });
}

function setCorsHeaders(response: NextResponse) {
  response.headers.set('Access-Control-Allow-Origin', '*');
  response.headers.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
  response.headers.set('Access-Control-Allow-Headers', 'Content-Type, x-api-key, Authorization');
  return response;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validationResult = ReservationReminderSchema.safeParse(body);
    
    if (!validationResult.success) {
      return setCorsHeaders(NextResponse.json({
        success: false,
        error: { code: 'VALIDATION_ERROR', message: 'Invalid data', details: validationResult.error.errors }
      }, { status: 400 }));
    }
    
    const { email, subject, message, site_id, locale } = validationResult.data;

    // Get site info
    const { data: siteInfo } = await supabaseAdmin.from('sites').select('*').eq('id', site_id).single();

    // Use sendGridService directly to avoid TeamNotificationService broadcasting
    const sendResult = await sendGridService.sendEmail({
      to: email,
      subject: subject,
      html: generateReservationHtml({
        siteName: siteInfo?.name || 'Your Site',
        subject: subject,
        message: message,
        locale: locale,
        logoUrl: siteInfo?.logo_url
      }),
      from: {
        email: 'no-reply@makinari.com',
        name: siteInfo?.name || 'Makinari'
      },
      categories: ['reservation', 'reminder'],
      customArgs: { siteId: site_id }
    });

    if (sendResult.success) {
      return setCorsHeaders(NextResponse.json({
        success: true,
        data: { sent_to: email, site_id }
      }));
    } else {
      return setCorsHeaders(NextResponse.json({
        success: false,
        error: { code: 'NOTIFICATION_SEND_ERROR', message: sendResult.error }
      }, { status: 500 }));
    }
  } catch (error) {
    return setCorsHeaders(NextResponse.json({
      success: false,
      error: { code: 'SYSTEM_ERROR', message: 'Internal error' }
    }, { status: 500 }));
  }
}
