-- Fix token columns type in commands table
-- Ensure the columns exist and have the right type

-- Primero verificamos si las columnas existen
DO $$
DECLARE
    input_column_exists BOOLEAN;
    input_column_type TEXT;
    output_column_exists BOOLEAN;
    output_column_type TEXT;
BEGIN
    -- Verificar input_tokens
    SELECT EXISTS(
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'commands' AND column_name = 'input_tokens'
    ) INTO input_column_exists;
    
    IF input_column_exists THEN
        SELECT data_type INTO input_column_type FROM information_schema.columns 
        WHERE table_name = 'commands' AND column_name = 'input_tokens';
        
        RAISE NOTICE 'Column input_tokens exists with type %', input_column_type;
    ELSE
        RAISE NOTICE 'Column input_tokens does not exist, creating...';
        ALTER TABLE commands ADD COLUMN input_tokens NUMERIC;
        COMMENT ON COLUMN commands.input_tokens IS 'Input tokens used by the command';
    END IF;
    
    -- Verificar output_tokens
    SELECT EXISTS(
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'commands' AND column_name = 'output_tokens'
    ) INTO output_column_exists;
    
    IF output_column_exists THEN
        SELECT data_type INTO output_column_type FROM information_schema.columns 
        WHERE table_name = 'commands' AND column_name = 'output_tokens';
        
        RAISE NOTICE 'Column output_tokens exists with type %', output_column_type;
    ELSE
        RAISE NOTICE 'Column output_tokens does not exist, creating...';
        ALTER TABLE commands ADD COLUMN output_tokens NUMERIC;
        COMMENT ON COLUMN commands.output_tokens IS 'Output tokens generated by the command';
    END IF;
    
    -- Ejecutar consulta de prueba para ver si las columnas funcionan
    DECLARE
        test_result RECORD;
    BEGIN
        -- Intentar actualizar un comando existente (si hay alguno)
        UPDATE commands 
        SET input_tokens = 100, output_tokens = 50 
        WHERE id IN (SELECT id FROM commands LIMIT 1)
        RETURNING id, input_tokens, output_tokens INTO test_result;
        
        IF FOUND THEN
            RAISE NOTICE 'Test update successful: id=%, input_tokens=%, output_tokens=%', 
                test_result.id, test_result.input_tokens, test_result.output_tokens;
        ELSE
            RAISE NOTICE 'No command found for test update';
        END IF;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Error in test update: %', SQLERRM;
    END;
END $$;
