export const SYSTEM_LABELS: Record<string, string> = {
  database_main: 'Main Database',
  database_apps: 'Apps Database',
  env_core: 'Core Environment',
  api_auth: 'API Authentication',
  public_api: 'Public API',
  agents: 'Agents API',
  workflow: 'Workflow API',
  integrations: 'Integrations',
  site: 'Site API',
  visitors: 'Visitors API',
  finder: 'Finder API',
  robots: 'Robots API',
  cron: 'Cron Jobs',
  platform: 'Platform API',
  notifications: 'Notifications',
  ai_portkey: 'AI Portkey',
  ai_text: 'AI Text',
  ai_text_continuation: 'AI Text Continuation',
  ai_image: 'AI Image',
  ai_video: 'AI Video',
  ai_audio: 'AI Audio',
};
